### ISSUE TITLE
New file created

### ISSUE THREAD

**Issue by jburel** [ome/build-infra#4]
Running for example
```printf 'org.openmicroscopy\tomero-model\t5.5.0-m6\n' | foreach-set-version```
create a new file ``build.gradlee`` in the directory of ``omero-model``

**Comment by joshmoore** [comment]
I've searched for this a few times and not found it. I'm pretty sure it began before `build-infra`, i.e. I think it's deeper in the gradle stack somewhere.

**Comment by joshmoore** [comment]
Still struggling with this one...
